### ISSUE TITLE
Update to last cairo version

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/resolver_delegation_cairo1#7]
## Description 📹

**Update the project to the latest version of Cairo.**  
Ensure compatibility with all components and update dependencies accordingly.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  

- [ ] Update the Cairo version in the project configuration.  
- [ ] Modify any breaking changes introduced by the new version of Cairo in the codebase.  
- [ ] Update relevant documentation to reflect the changes in the new Cairo version.  
- [ ] If any migrations or specific setup steps are required for the update, include them in the project setup documentation.  

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
```bash
   git commit -m "Fix: Update to the latest Cairo version"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Emmanex01** [comment]
I'd like to handle this task.

**Comment by OWK50GA** [comment]
May I take this issue on?
I'm a Frontend Web Developer and Cairo Smart Contract Developer, and I can handle this.
I will change the Cairo version in the Scarb.toml and check for any errors it causes by running scarb build. I'll fix these errors across the project by tweaking the code to fit the version without changing the function/output

**Comment by Benjtalkshow** [comment]
Can I handle this task?

**Comment by Kritto** [comment]
I will update this project to the latest version of Cairo, ensuring all components are compatible and dependencies are properly updated. 

I'll address any breaking changes, modify the codebase as needed, and update the documentation to reflect the changes. Once the updates are complete, I'll run tests to verify functionality and submit the changes with a clear commit message.

Assign me this task, let's get started on updating to the latest Cairo version and ensure everything runs smoothly.

**Comment by mimisavage** [comment]
Can I jump on this task?

**Comment by ikemHood** [comment]
I’d like to help with this.

**Comment by suhas-sensei** [comment]
I would love to work on this. I will update the project to the latest Cairo version, resolve any breaking changes, and ensure compatibility across all components with comprehensive testing.
draft pr in 24hours

**Comment by Birdmannn** [comment]
Please Can I be assigned to this?

**Comment by PoulavBhowmick03** [comment]
I would love to work on this! I am a contributor to lfg_labs and the Starknet ecosystem, and have a good experience working with cairo (https://app.onlydust.com/u/PoulavBhowmick03)
