### ISSUE TITLE
Add a script category to the README

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/resolver_delegation_cairo1#8]
## Description 📹

Add a short section to the README to specify that there are deployment scripts in the `scripts` folder, which can be used to deploy the contracts more efficiently.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:

   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   Update the `README.md` file by adding a section about deployment scripts. E.g.
   Suggested text:
   ```markdown
   ## Deployment Scripts

   The `scripts` folder contains deployment scripts that simplify and streamline the process of deploying the contracts. Use these scripts to ensure efficient and consistent deployment.
   ```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:

   ```bash
   git commit -m "Fix: Add deployment scripts section to README"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by petersdt** [comment]
@fricoben kindly assign me this task. i would like to handle it.

I would create an easy to understand read that will direct users to [scripts](https://github.com/lfglabs-dev/resolver_delegation_cairo1/tree/main/scripts)

ETA <= 2hrs

**Comment by CollinsC1O** [comment]
Hi @Marchand-Nicolas I'm a front-end and a blockchain developer. I will love to take on this issue

**Comment by NueloSE** [comment]
@Marchand-Nicolas can i be assigned this issue

ETA <= 2days

**Comment by SudiptaPaul-31** [comment]
Can I start working on this?

**Comment by Emmanex01** [comment]
May I try my hand at this?

**Comment by Benjtalkshow** [comment]
Could I take on this issue?

**Comment by Kritto** [comment]
I will update the README to include a section highlighting the deployment scripts in the `scripts` folder, ensuring users can deploy contracts more efficiently. 

This change will provide clear guidance on utilizing the scripts for a streamlined and consistent deployment process. After implementing the update, I will run tests to confirm functionality and follow the proper steps to commit and submit a pull request for review.

Let's add this deployment section to the README and streamline the deployment process - I'll get started right away!

**Comment by petersdt** [comment]
@fricoben kindly assign me this task. i would like to handle it.

I would create an easy to understand read that will direct users to [scripts](https://github.com/lfglabs-dev/resolver_delegation_cairo1/tree/main/scripts)

ETA <= 2hrs

**Comment by mimisavage** [comment]
Let me try this one!

**Comment by mayasimi** [comment]
Can I start working on this?

**Comment by NueloSE** [comment]
Is it okay if I take this?

**Comment by suhas-sensei** [comment]
Could I try solving this?

**Comment by Iwueseiter** [comment]
Can I take this from here?
